#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, but with a while loop and now it goes weird in the 9th
i=1
while [ "$i" -le 10 ]; do 
	if [ "$i" -eq 9 ]; then
		echo "Hi"
	else
		echo "Holberton School"
	fi
	i=$((i+1))
done
