#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, but with a while loop and now it goes weird in the 9th
i=1
while [ "$i" -le 10 ]; do 
	if [ "$i" -eq 4 ]; then echo "bad luck"; fi
	if [ "$i" -eq 8 ]; then echo "good luck"; fi
	if [ "$i" -ne 4 ] && [ "$i" -ne 8 ]; then
		echo "Holberton School"
	fi
	i=$((i+1))
done
